---
- hosts: localhost
  gather_facts: false

  tasks:
    - apt:
        name: nginx
        state: installed

    - service: name=nginx state=started enabled=yes

    - name: Deploy static website
      copy:
        src: .
        dest: /usr/share/nginx/html/
    - name: Build nginx
      become: no
      shell: |
        docker rm -f $(sudo docker ps -a -q)
        docker build /home/ubuntu/jenkins/workspace/ansible-deploy-on-production-server/. -t prod:$(sudo git rev-parse --short HEAD)
        docker run -it -p 85:80 -d prod:$(sudo git rev-parse --short HEAD)
